/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Apple: typeof import('./src/components/icons/apple/index.vue')['default']
    ArrowRight: typeof import('./src/components/icons/arrow-right/index.vue')['default']
    Avatar: typeof import('./src/components/avatar/avatar.vue')['default']
    Button: typeof import('./src/components/button/button.vue')['default']
    Checkbox: typeof import('./src/components/checkbox/checkbox.vue')['default']
    CountDown: typeof import('./src/components/count-down/count-down.vue')['default']
    Divider: typeof import('./src/components/divider/divider.vue')['default']
    Eye: typeof import('./src/components/icons/eye/index.vue')['default']
    EyeSlash: typeof import('./src/components/icons/eye-slash/index.vue')['default']
    Google: typeof import('./src/components/icons/google/index.vue')['default']
    InputInfo: typeof import('./src/components/input-info/input-info.vue')['default']
    InputPassword: typeof import('./src/components/input-password/input-password.vue')['default']
    InputText: typeof import('./src/components/input-text/input-text.vue')['default']
    LinkText: typeof import('./src/components/link-text/link-text.vue')['default']
    Logo: typeof import('./src/components/logo/logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spinner: typeof import('./src/components/icons/spinner/index.vue')['default']
    Tab: typeof import('./src/components/tab/tab.vue')['default']
    TelInput: typeof import('./src/components/tel-input/tel-input.vue')['default']
    TickSquared: typeof import('./src/components/icons/tick-squared/index.vue')['default']
    Toast: typeof import('./src/components/toast/toast.vue')['default']
    Warning: typeof import('./src/components/icons/warning/index.vue')['default']
  }
}
