export { default as Header } from './header.vue'
export { default as IntroductionVideo } from './introduction-video.vue'
export { default as Statistics } from './statistics.vue'
export { default as Rating } from './rating.vue'
export { default as Comments } from './comments.vue'
export { default as CustomPlayer } from './custom-player.vue'
