services:
  pwa:
    image: registry.go2tr.ir/g2/train/pwa/pwa:${CI_PIPELINE_ID}-dev
    container_name: pwa
    restart: always
    # env_file:
    #   - ./.env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.pwa.entrypoints=websecure"
      - "traefik.http.routers.pwa.rule=Host(`train-pwa.go2tr.work`)"
      - "traefik.http.services.pwa.loadbalancer.server.port=3000"
      - "traefik.http.routers.pwa.tls=true"
      - "traefik.http.routers.pwa.tls.certresolver=cloudflare"
    networks:
      - proxy
    

networks:
  proxy:
    external: true